# Generated by Django 6.0.3 on 2026-03-24 21:44

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento de Log',
                'verbose_name_plural': 'Eventos de Log',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ruta_base_nas', models.CharField(help_text='Ruta raíz en el NAS para esta sucursal', max_length=500)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esquema_metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(max_length=255)),
                ('ci', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='posts.departamento')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='posts.sucursal')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'permissions': [('puede_aprobar_documentos', 'Puede aprobar documentos pendientes'), ('puede_ver_logs', 'Puede ver los logs del sistema'), ('puede_gestionar_usuarios', 'Puede crear y editar usuarios'), ('puede_gestionar_tipos_documento', 'Puede gestionar tipos de documento'), ('puede_ver_historial', 'Puede ver historial de cambios de documentos'), ('puede_ver_visualizaciones', 'Puede ver quién visualizó documentos')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre_nas', models.SlugField(help_text='Nombre físico en el NAS (sin espacios ni tildes)', max_length=150)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcarpetas', to='posts.carpeta')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='posts.departamento')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='posts.sucursal')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo_nas', models.CharField(max_length=255, unique=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('numero_operacion', models.CharField(db_index=True, max_length=200)),
                ('numero_identificacion_socio', models.CharField(db_index=True, max_length=200)),
                ('nombre_socio', models.CharField(max_length=255)),
                ('metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_version_vigente', models.BooleanField(db_index=True, default=True, help_text='Si es True, este es el archivo que verán los usuarios normales.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En edición)'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_CORRECCION', 'En corrección')], db_index=True, default='BORRADOR', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('bloqueado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_bloqueados', to=settings.AUTH_USER_MODEL)),
                ('id_documento_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_versiones', to='posts.archivo')),
                ('id_usuario_aprobacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('id_usuario_subida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
                ('id_carpeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='posts.carpeta')),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='posts.sucursal')),
                ('id_tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='posts.tipodocumento')),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('puede_eliminar_cualquier_documento', 'Puede eliminar documentos de cualquier usuario'), ('puede_editar_cualquier_documento', 'Puede editar documentos de cualquier usuario'), ('puede_ver_documentos_restringidos', 'Puede ver documentos que normalmente no le corresponden')],
            },
        ),
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('INTENTO_FALLIDO', 'Intento fallido')], max_length=20)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('exito', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='posts.archivo')),
            ],
            options={
                'verbose_name': 'Acceso a documento',
                'verbose_name_plural': 'Accesos a documentos',
                'indexes': [models.Index(fields=['documento', 'tipo'], name='posts_acces_documen_ff7feb_idx'), models.Index(fields=['usuario', 'fecha_acceso'], name='posts_acces_usuario_9d37df_idx')],
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=10)),
                ('detalle', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.eventolog')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'indexes': [models.Index(fields=['fecha_hora'], name='posts_log_fecha_h_416b14_idx'), models.Index(fields=['usuario', 'fecha_hora'], name='posts_log_usuario_57c559_idx'), models.Index(fields=['evento', 'resultado'], name='posts_log_evento__28abd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APROBACION', 'Documento aprobado'), ('RECHAZO', 'Documento rechazado'), ('SOLICITUD_CAMBIO', 'Solicitud de cambios'), ('ACCESO_LOG', 'Acceso temporal a logs'), ('NUEVO_DOC', 'Nuevo documento pendiente')], max_length=30)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='posts.archivo')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'indexes': [models.Index(fields=['usuario_destino', 'leida'], name='posts_notif_usuario_c8c4c0_idx'), models.Index(fields=['fecha_envio'], name='posts_notif_fecha_e_fb2d68_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='carpeta',
            index=models.Index(fields=['activo'], name='posts_carpe_activo_a29316_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together={('nombre_nas', 'padre', 'sucursal')},
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['numero_identificacion_socio', 'numero_operacion'], name='posts_archi_numero__f88b00_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['estado', 'activo'], name='posts_archi_estado_edb852_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['fecha_subida'], name='posts_archi_fecha_s_91eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(condition=models.Q(('metadatos__isnull', False)), fields=['metadatos'], name='archivo_metadatos_gin'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['es_version_vigente', 'activo', 'id_carpeta'], name='posts_archi_es_vers_18246c_idx'),
        ),
    ]
