# Generated by Django 6.0.3 on 2026-03-27 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento de Log',
                'verbose_name_plural': 'Eventos de Log',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=10)),
                ('detalle', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APROBACION', 'Documento aprobado'), ('RECHAZO', 'Documento rechazado'), ('SOLICITUD_CAMBIO', 'Solicitud de cambios'), ('ACCESO_LOG', 'Acceso temporal a logs'), ('NUEVO_DOC', 'Nuevo documento pendiente')], max_length=30)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('INTENTO_FALLIDO', 'Intento fallido')], max_length=20)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('exito', models.BooleanField(default=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='archivo.archivo')),
            ],
            options={
                'verbose_name': 'Acceso a documento',
                'verbose_name_plural': 'Accesos a documentos',
            },
        ),
    ]
