# Generated by Django 6.0.3 on 2026-03-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VISUALIZACION', 'Visualización'), ('DESCARGA', 'Descarga'), ('INTENTO_FALLIDO', 'Intento fallido')], max_length=20)),
                ('fecha_acceso', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('exito', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Acceso a documento',
                'verbose_name_plural': 'Accesos a documentos',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo_nas', models.CharField(max_length=255, unique=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('numero_operacion', models.CharField(db_index=True, max_length=200)),
                ('numero_identificacion_socio', models.CharField(db_index=True, max_length=200)),
                ('nombre_socio', models.CharField(max_length=255)),
                ('metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_version_vigente', models.BooleanField(db_index=True, default=True, help_text='Si es True, este es el archivo que verán los usuarios normales.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En edición)'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_CORRECCION', 'En corrección')], db_index=True, default='BORRADOR', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('puede_eliminar_cualquier_documento', 'Puede eliminar documentos de cualquier usuario'), ('puede_editar_cualquier_documento', 'Puede editar documentos de cualquier usuario'), ('puede_ver_documentos_restringidos', 'Puede ver documentos que normalmente no le corresponden')],
            },
        ),
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nombre_nas', models.SlugField(help_text='Nombre físico en el NAS (sin espacios ni tildes)', max_length=150)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Evento de Log',
                'verbose_name_plural': 'Eventos de Log',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_ip', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=10)),
                ('detalle', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('APROBACION', 'Documento aprobado'), ('RECHAZO', 'Documento rechazado'), ('SOLICITUD_CAMBIO', 'Solicitud de cambios'), ('ACCESO_LOG', 'Acceso temporal a logs'), ('NUEVO_DOC', 'Nuevo documento pendiente')], max_length=30)),
                ('asunto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ruta_base_nas', models.CharField(help_text='Ruta raíz en el NAS para esta sucursal', max_length=500)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esquema_metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
    ]
