# Generated by Django 6.0.3 on 2026-03-27 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesodocumento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='bloqueado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_documento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_versiones', to='posts.archivo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_usuario_subida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesodocumento',
            name='documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to='posts.archivo'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcarpetas', to='posts.carpeta'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='posts.carpeta'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='posts.departamento'),
        ),
        migrations.AddField(
            model_name='log',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.eventolog'),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='posts.archivo'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='posts.sucursal'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='posts.sucursal'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='posts.tipodocumento'),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['documento', 'tipo'], name='posts_acces_documen_ff7feb_idx'),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['usuario', 'fecha_acceso'], name='posts_acces_usuario_9d37df_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['fecha_hora'], name='posts_log_fecha_h_416b14_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='posts_log_usuario_57c559_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['evento', 'resultado'], name='posts_log_evento__28abd6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario_destino', 'leida'], name='posts_notif_usuario_c8c4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_envio'], name='posts_notif_fecha_e_fb2d68_idx'),
        ),
        migrations.AddIndex(
            model_name='carpeta',
            index=models.Index(fields=['activo'], name='posts_carpe_activo_a29316_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carpeta',
            unique_together={('nombre_nas', 'padre', 'sucursal')},
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['numero_identificacion_socio', 'numero_operacion'], name='posts_archi_numero__f88b00_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['estado', 'activo'], name='posts_archi_estado_edb852_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['fecha_subida'], name='posts_archi_fecha_s_91eb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(condition=models.Q(('metadatos__isnull', False)), fields=['metadatos'], name='archivo_metadatos_gin'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['es_version_vigente', 'activo', 'id_carpeta'], name='posts_archi_es_vers_18246c_idx'),
        ),
    ]
