# Generated by Django 6.0.3 on 2026-03-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivo', '0002_initial'),
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesodocumento',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='log',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='posts.eventolog'),
        ),
        migrations.AddField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='archivo.archivo'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['documento', 'tipo'], name='posts_acces_documen_ff7feb_idx'),
        ),
        migrations.AddIndex(
            model_name='accesodocumento',
            index=models.Index(fields=['usuario', 'fecha_acceso'], name='posts_acces_usuario_9d37df_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['fecha_hora'], name='posts_log_fecha_h_416b14_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['usuario', 'fecha_hora'], name='posts_log_usuario_57c559_idx'),
        ),
        migrations.AddIndex(
            model_name='log',
            index=models.Index(fields=['evento', 'resultado'], name='posts_log_evento__28abd6_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario_destino', 'leida'], name='posts_notif_usuario_c8c4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['fecha_envio'], name='posts_notif_fecha_e_fb2d68_idx'),
        ),
    ]
