# Generated by Django 6.0.3 on 2026-03-23 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('modulo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_auth', models.IntegerField(blank=True, null=True)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('EXITO', 'Éxito'), ('ERROR', 'Error')], max_length=10)),
                ('detalle', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.CharField(blank=True, max_length=150, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.eventolog')),
            ],
        ),
    ]
