# Generated by Django 6.0.3 on 2026-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nombre_nas', models.SlugField(help_text='Nombre físico en el NAS (sin espacios ni tildes)', max_length=150)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
            },
        ),
        migrations.CreateModel(
            name='PermisoCarpeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('LECTURA', 'Solo Ver'), ('ESCRITURA', 'Ver, Subir y Editar Archivos'), ('ADMIN', 'Control Total')], default='LECTURA', max_length=20)),
            ],
            options={
                'verbose_name': 'Permiso de Carpeta',
                'verbose_name_plural': 'Permisos de Carpetas',
            },
        ),
    ]
