# Generated by Django 6.0.3 on 2026-03-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('departamento_sucursal', '0001_initial'),
        ('directorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carpeta',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carpetas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='departamento_sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='carpetas', to='departamento_sucursal.departamentosucursal'),
        ),
        migrations.AddField(
            model_name='carpeta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcarpetas', to='directorios.carpeta'),
        ),
        migrations.AddField(
            model_name='permisocarpeta',
            name='carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='directorios.carpeta'),
        ),
        migrations.AddField(
            model_name='permisocarpeta',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_carpetas', to='auth.group'),
        ),
        migrations.AddField(
            model_name='permisocarpeta',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_directos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='carpeta',
            index=models.Index(fields=['activo'], name='directorios_activo_d2e577_idx'),
        ),
        migrations.AddConstraint(
            model_name='carpeta',
            constraint=models.UniqueConstraint(fields=('nombre_nas', 'padre', 'departamento_sucursal'), name='unique_nombre_nas_padre_departamento_sucursal'),
        ),
        migrations.AddIndex(
            model_name='permisocarpeta',
            index=models.Index(fields=['carpeta', 'usuario'], name='directorios_carpeta_e6c1c0_idx'),
        ),
        migrations.AddIndex(
            model_name='permisocarpeta',
            index=models.Index(fields=['carpeta', 'grupo'], name='directorios_carpeta_2dd8d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='permisocarpeta',
            constraint=models.UniqueConstraint(condition=models.Q(('usuario__isnull', False)), fields=('carpeta', 'usuario'), name='unique_permiso_usuario'),
        ),
        migrations.AddConstraint(
            model_name='permisocarpeta',
            constraint=models.UniqueConstraint(condition=models.Q(('grupo__isnull', False)), fields=('carpeta', 'grupo'), name='unique_permiso_grupo'),
        ),
    ]
