# Generated by Django 6.0.3 on 2026-03-27 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo_nas', models.CharField(max_length=255, unique=True)),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('numero_operacion', models.CharField(db_index=True, max_length=200)),
                ('numero_identificacion_socio', models.CharField(db_index=True, max_length=200)),
                ('nombre_socio', models.CharField(max_length=255)),
                ('metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('es_version_vigente', models.BooleanField(db_index=True, default=True, help_text='Si es True, este es el archivo que verán los usuarios normales.')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador (En edición)'), ('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_CORRECCION', 'En corrección')], db_index=True, default='BORRADOR', max_length=20)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('fecha_bloqueo', models.DateTimeField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Archivo',
                'verbose_name_plural': 'Archivos',
                'permissions': [('puede_eliminar_cualquier_documento', 'Puede eliminar documentos de cualquier usuario'), ('puede_editar_cualquier_documento', 'Puede editar documentos de cualquier usuario'), ('puede_ver_documentos_restringidos', 'Puede ver documentos que normalmente no le corresponden')],
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('esquema_metadatos', models.JSONField(blank=True, default=dict, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
    ]
