# Generated by Django 6.0.3 on 2026-03-27 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archivo', '0001_initial'),
        ('directorios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='bloqueado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_carpeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='directorios.carpeta'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_documento_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_versiones', to='archivo.archivo'),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_usuario_aprobacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_usuario_subida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='archivo',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='archivo.tipodocumento'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['numero_identificacion_socio', 'numero_operacion'], name='archivo_arc_numero__c0f1c8_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['estado', 'activo'], name='archivo_arc_estado_ffc1ff_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['fecha_subida'], name='archivo_arc_fecha_s_68f3a0_idx'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(condition=models.Q(('metadatos__isnull', False)), fields=['metadatos'], name='archivo_metadatos_gin'),
        ),
        migrations.AddIndex(
            model_name='archivo',
            index=models.Index(fields=['es_version_vigente', 'activo', 'id_carpeta'], name='archivo_arc_es_vers_bd0c7a_idx'),
        ),
    ]
